version: '3'

vars:
  GOOS: "{{default OS .GOOS}}"
  MVNW: '{{if eq .GOOS "windows"}}mvnw.cmd{{else}}./mvnw{{end}}'
  IMAGE_NAME: 'sivaprasadreddy/techbuzz'
  DC_DIR: "deployment/docker-compose"
  DC_FILE: "{{.DC_DIR}}/docker-compose.yml"

tasks:
  default:
    cmds:
      - task: test
  test:
    deps: [format]
    cmds:
      - "{{.MVNW}} clean verify"

  format:
    cmds:
      - "{{.MVNW}} spotless:apply"

  build_image:
    cmds:
      - "{{.MVNW}} -pl techbuzz clean compile spring-boot:build-image -DskipTests -DdockerImageName={{.IMAGE_NAME}}"

  start_infra:
    cmds:
      - docker compose -f "{{.DC_FILE}}" up -d

  stop_infra:
    cmds:
      - docker compose -f "{{.DC_FILE}}" stop
      - docker compose -f "{{.DC_FILE}}" rm -f

  restart_infra:
    cmds:
      - task: stop_infra
      - task: sleep
      - task: start_infra

  start:
    deps: [build_image]
    cmds:
      - docker compose --profile app -f "{{.DC_FILE}}" up --force-recreate -d

  stop:
    cmds:
      - docker compose --profile app -f "{{.DC_FILE}}" stop
      - docker compose --profile app -f "{{.DC_FILE}}" rm -f

  restart:
    cmds:
      - task: stop
      - task: sleep
      - task: start

  sleep:
    vars:
      DURATION: '{{default 5 .DURATION}}'
    cmds:
      - sleep {{.DURATION}}